-- 003: 同じユーザーが同じ元投稿を何度リポストしても posts が増えないよう DB 側で止める。
-- 通常投稿と返信は original_post_id が NULL で、UNIQUE は NULL 同士を別の値として扱うため影響しない。
-- 【要事前確認】既に重複行があると下の ALTER は "Duplicate entry" で失敗する。先にこれを流し、
-- 1 行でも返ったらグループごとに MIN(id) だけ残して削除すること（このスキーマに外部キーは無く、
-- 消した posts.id を指す likes / reposts / notifications / 返信は黙って孤児になる）:
--   SELECT user_id, original_post_id, COUNT(*), MIN(id) FROM posts
--   WHERE original_post_id IS NOT NULL GROUP BY user_id, original_post_id HAVING COUNT(*) > 1;
-- 【注意】initdb マウント経由の SQL はボリューム初回作成時にしか走らず、既存 DB では黙って
-- 読み飛ばされる。手動適用すること（IF NOT EXISTS が無いので 2 回目は 1061 で失敗する）:
--   docker compose exec -T db mysql -u sakuravel -ppassword sakuravel < migrations/003_repost_unique.sql
ALTER TABLE posts ADD UNIQUE KEY uq_posts_user_original (user_id, original_post_id);
